name: Build & Push to GitHub Packages

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Build
      run: docker build . -t docker.pkg.github.com/kirisame-project/switchboard/${GITHUB_REF##*/}-nightly
    - name: Push to GitHub Packages
      run: |
        docker login docker.pkg.github.com -u amphineko -p ${{ secrets.GITHUB_TOKEN }}
        docker push docker.pkg.github.com/kirisame-project/switchboard/${GITHUB_REF##*/}-nightly
